spring:
  profiles:
    active: mysql
  application:
    name: weishuo-backend
  datasource:
    url: jdbc:h2:mem:weishuo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

news:
  api:
    base-url: http://api.mediastack.com/v1
    api-key: 2c5da11d7fe03442c8b1f3433ecaa40c
    country: cn
    language: zh
    page-size: 10
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: info

---
spring:
  config:
    activate:
      on-profile: mysql
server:
  port: 8081
  datasource:
    url: jdbc:mysql://localhost:3306/weishuo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD:111111}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update